# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\OneDrive - BUas\MGT\Scripts\SwatchM8\resources\qt\ui_main.ui',
# licensing of 'D:\OneDrive - BUas\MGT\Scripts\SwatchM8\resources\qt\ui_main.ui' applies.
#
# Created: Sun Jan  3 04:56:37 2021
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 324)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 164, 26))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.TextureHBox = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.TextureHBox.setContentsMargins(0, 0, 0, 0)
        self.TextureHBox.setObjectName("TextureHBox")
        self.SelectedTextureNameLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.SelectedTextureNameLabel.setObjectName("SelectedTextureNameLabel")
        self.TextureHBox.addWidget(self.SelectedTextureNameLabel)
        self.TextureSettingsButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.TextureSettingsButton.setObjectName("TextureSettingsButton")
        self.TextureHBox.addWidget(self.TextureSettingsButton)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 241, 221))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.ModelsTab = QtWidgets.QWidget()
        self.ModelsTab.setObjectName("ModelsTab")
        self.ModelsTree = QtWidgets.QTreeWidget(self.ModelsTab)
        self.ModelsTree.setGeometry(QtCore.QRect(0, 0, 235, 195))
        self.ModelsTree.setStyleSheet("width:100%;")
        self.ModelsTree.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ModelsTree.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ModelsTree.setExpandsOnDoubleClick(False)
        self.ModelsTree.setObjectName("ModelsTree")
        self.ModelsTree.headerItem().setText(0, "Name")
        self.tabWidget.addTab(self.ModelsTab, "")
        self.SwatchesTab = QtWidgets.QWidget()
        self.SwatchesTab.setObjectName("SwatchesTab")
        self.SwatchTree = QtWidgets.QTreeWidget(self.SwatchesTab)
        self.SwatchTree.setGeometry(QtCore.QRect(0, 0, 231, 191))
        self.SwatchTree.setStyleSheet("width:100%;")
        self.SwatchTree.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SwatchTree.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SwatchTree.setExpandsOnDoubleClick(False)
        self.SwatchTree.setObjectName("SwatchTree")
        self.SwatchTree.headerItem().setText(0, "Name")
        self.tabWidget.addTab(self.SwatchesTab, "")
        self.RightFrame = QtWidgets.QStackedWidget(self.centralwidget)
        self.RightFrame.setGeometry(QtCore.QRect(260, 20, 311, 271))
        self.RightFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.RightFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.RightFrame.setObjectName("RightFrame")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.RightFrame.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.RightFrame.addWidget(self.page_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 270, 248, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ApplyMaterialButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.ApplyMaterialButton.setObjectName("ApplyMaterialButton")
        self.horizontalLayout.addWidget(self.ApplyMaterialButton)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.AddPartButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.AddPartButton.setObjectName("AddPartButton")
        self.horizontalLayout.addWidget(self.AddPartButton)
        self.AddSwatchButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.AddSwatchButton.setObjectName("AddSwatchButton")
        self.horizontalLayout.addWidget(self.AddSwatchButton)
        self.PopUpFrame = QtWidgets.QStackedWidget(self.centralwidget)
        self.PopUpFrame.setGeometry(QtCore.QRect(0, 0, 601, 321))
        self.PopUpFrame.setObjectName("PopUpFrame")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.PopUpFrame.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.PopUpFrame.addWidget(self.page_6)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.RightFrame.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.SelectedTextureNameLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Texture Name", None, -1))
        self.TextureSettingsButton.setText(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.ModelsTree.headerItem().setText(1, QtWidgets.QApplication.translate("MainWindow", "Swatch", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ModelsTab), QtWidgets.QApplication.translate("MainWindow", "Models", None, -1))
        self.SwatchTree.headerItem().setText(1, QtWidgets.QApplication.translate("MainWindow", "Model", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SwatchesTab), QtWidgets.QApplication.translate("MainWindow", "Swatches", None, -1))
        self.ApplyMaterialButton.setText(QtWidgets.QApplication.translate("MainWindow", "Apply Mat", None, -1))
        self.AddPartButton.setText(QtWidgets.QApplication.translate("MainWindow", "Add Part", None, -1))
        self.AddSwatchButton.setText(QtWidgets.QApplication.translate("MainWindow", "Add Swatch", None, -1))

